### ISSUE TITLE
Phoenix Plugs integration not working

### ISSUE THREAD

**Issue by ludwikbukowski** [spandex-project/spandex_ecto#2]
I tried to use just `spandex` with `spandex_datadog` adapter with usage of `Spandex.Plugs` and it works really nice. However, when I tried to combine it with `spandex_ecto` looks like nothing is sent from the agent to datadog.

My configuation:
```
config :spandex_ecto, SpandexEcto.EctoLogger,
  service: :ecto, 
  tracer: Myapp.Tracer,
  otp_app: :datadog

config :datadog, MyApp.Tracer
  service: :myapp,
  adapter: SpandexDatadog.Adapter,
  disabled?: false,
  env: "DEV"

config :myapp,
  datadog_host: "localhost",
  datadog_port: 8126
```

Can you confirm that mixing `Spandex.Plugs` with `spandex_ecto` will work?
Using `:dbg` I can see that `SpandexEcto.EctoLogger.trace` is called and spans are updated but in the end I cannot see it in the Datadog

**Comment by ludwikbukowski** [comment]
Hmm, that might be true that the db calls are done in context of different process. I guess it might not be working with process dictionary strategy then.

**Comment by zachdaniel** [comment]
Have you added the spandex Ecto logger to ectos list of loggers?

**Comment by ludwikbukowski** [comment]
Yes, like this:
```
  loggers: [{Ecto.LogEntry, :log, []}, {SpandexEcto.EctoLogger, :trace, ["database_name"]}]
```

and as written before, `SpandexEcto.EctoLogger.trace` is correctly called.
Moreover, I can see that the `update_span`s are called correctly:
```
(<0.3728.0>) call 'Elixir.WunderMetrics.Decorators':update_span([{service,ecto},
 {start,1538516817147359769},
 {completion_time,1538516817147439000}])
```
and in context of the same process as the rest of the spans...

**Comment by zachdaniel** [comment]
Hmm.... and the call to Ecto is happening in the same process as the process that started the trace?

**Comment by ludwikbukowski** [comment]
Now I can see that there is no `caller_pid` field in `Ecto.EntryLog` passed to `trace` function.
Because of that, this branch is executed:
https://github.com/spandex-project/spandex_ecto/blob/master/lib/spandex_ecto/ecto_logger.ex#L115

**Comment by zachdaniel** [comment]
Interesting. I'd have to think about it a bit more, but it *seems* like that branch should be starting a span in the same way that one is started when `caller_pid == self()`

**Comment by ludwikbukowski** [comment]
no, you pattern match here on `caller_pid`:
https://github.com/spandex-project/spandex_ecto/blob/master/lib/spandex_ecto/ecto_logger.ex#L98
but its not available in the map so automatically this branch matches:
https://github.com/spandex-project/spandex_ecto/blob/master/lib/spandex_ecto/ecto_logger.ex#L115

hence no root span is started

**Comment by zachdaniel** [comment]
We've talked about having a monitor registry that stores information about running traces, which also allows for recovering from certain catastrophic failures in a process, so the long term ideal version of this would be to check if we are in a trace, and if not, ask the monitor/registry process what the trace info is for the pid that called us.

**Comment by ludwikbukowski** [comment]
Sounds like playing with some `:dbg` in order to monitor spawned processes.
Similar approach was used in this repo https://github.com/newrelic/elixir_agent which is tracing agent for NewRelic. They monitor once new process is spawned and they add it to their trace registry

**Comment by zachdaniel** [comment]
If we have a registry we shouldn't need to use any debugging tools really. For now this works, and a monitor process in spandex is a nontrivial project, so there isn't much we can do without that.
