### ISSUE TITLE
Not seeing traces with the latest.

### ISSUE THREAD

**Issue by EdBondRSA** [spandex-project/spandex_ecto#24]
This might be a user problem, however I am not seeing ecto queries populating.

```
config :spandex_ecto, SpandexEcto.EctoLogger, tracer: CloudHarmony.Tracer
```

I tried it with the service specified as well. 

```
    :ok =
      :telemetry.attach(
        "spandex-query-tracer",
        [:app, :repo_harmony, :query],
        &SpandexEcto.TelemetryAdapter.handle_event/4,
        nil
      )
```

![2020-08-07-163745_584x309_scrot](https://user-images.githubusercontent.com/62294602/89690531-5806f380-d8cc-11ea-8a48-763e43587f83.png)

mix.exs 
```
      {:spandex, "~> 3.0.2"},
      {:spandex_datadog, "~> 1.0.0"},
      {:spandex_phoenix, "~> 1.0.3"},
      {:spandex_ecto, "~> 0.6.2"},
```
  

Are there any ways to debug this, or am I not doing a complex enough ( just a Repo.get  essentially )

**Comment by cheerfulstoic** [comment]
Possibly something to do with #22?  Trying to figure this out myself now.  Did you ever figure it out?

**Comment by cheerfulstoic** [comment]
I'm also seeing `RutilexWeb.Tracer.current_trace_id()` as `nil` much of the time

**Comment by cheerfulstoic** [comment]
It also looks like `spandex_phoenix` has a recent 1.0.4 version of with a bug fix of "Close span instead of trace on router exception"

https://diff.hex.pm/diff/spandex_phoenix/1.0.3..1.0.4

**Comment by EdBondRSA** [comment]
I will have to upgrade and try.

**Comment by ivanhoe** [comment]
Hi guys @EdBondRSA and @cheerfulstoic im also trying to use the library to trace the Ecto queries but with not good results, im not receiving any data in the AMP trace dashboard 

My environment is elixir 1.9 and phoenix 1.4
My mix.exs file look like this:

```
     {:phoenix, "~> 1.4.0"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.0"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.6"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:bcrypt_elixir, "~> 2.0"},
      {:ex_json_schema, "~> 0.5.4"},
      {:poison, "~> 3.1.0", override: true},
      {:spandex, "~> 3.0.2"},
      {:decorator, "~> 1.2"},
      {:spandex_datadog, "~> 1.0.0"},
      {:spandex_phoenix, "~> 1.0.4"},
      {:spandex_ecto, "~> 0.6.2"},
      {:hackney, "~> 1.16"},
      {:httpoison, "~> 1.6"}
```

And the application.ex 

   ```
 :ok =
      :telemetry.attach(
        "spandex-query-tracer",
        [:elixir_json_schema, :repo_elixir_json_schema, :query],
        &SpandexEcto.TelemetryAdapter.handle_event/4,
        nil
      )
```
Do you have any progress or solution to make the library work? I appreciate so much any comment

**Comment by zachdaniel** [comment]
Are you potentially making the database calls in a different process? You have to manually continue the trace if you start a new process to do work. e.g

```
current_context = Tracer.current_context()

Task.async(fn -> 
  Tracer.continue_trace("ecto_query", current_context)
  MyRepo.get(Thing, 1)
end)
```

**Comment by ivanhoe** [comment]
Hi @zachdaniel first of all thanks for take the time to check my question. I have a basic testing project that is creating  a user with and endpoint. This project is running in docker and im printing the pid in the log and im looking its the same process. The project its in my [github](https://github.com/ivanhoe/elixir_json_schema/tree/development) is there any chance you could check If its something wrong in the configuration or something missing? 

```
elixir_json_schema_phoenix_1  | 19:14:48.291 request_id=FjZFRuBcBW62DEQAAAFC pid=<0.526.0> trace_id=5953393659571752646 span_id=5068237155539998118 [info] POST /api/users
elixir_json_schema_phoenix_1  | 19:14:48.315 request_id=FjZFRuBcBW62DEQAAAFC pid=<0.526.0> trace_id=5953393659571752646 span_id=5068237155539998118 [debug] Processing with ElixirJsonSchemaWeb.UserController.create/2
elixir_json_schema_phoenix_1  |   Parameters: %{"user" => %{"email" => "test13@mail.com", "is_active" => true, "password" => "[FILTERED]"}}
elixir_json_schema_phoenix_1  |   Pipelines: [:api]
elixir_json_schema_phoenix_1  | 19:14:48.406 request_id=FjZFRuBcBW62DEQAAAFC pid=<0.526.0> trace_id=5953393659571752646 span_id=1835807773515816832 [debug] QUERY OK db=8.6ms decode=5.2ms queue=1.4ms idle=1105.5ms
elixir_json_schema_phoenix_1  | INSERT INTO "users" ("email","is_active","inserted_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "id" ["test13@mail.com", true, ~N[2020-09-19 19:14:48], ~N[2020-09-19 19:14:48]]
elixir_json_schema_phoenix_1  | 19:14:48.419 request_id=FjZFRuBcBW62DEQAAAFC pid=<0.526.0> trace_id=5953393659571752646 span_id=8865612231795632374 [info] Sent 201 in 127ms
```

**Comment by zachdaniel** [comment]
@ivanhoe I don't see anything immediately out of place. Try adding `verbose?: true` to your ApiServer options (in your application startup). You'll get a whole lot of stuff printed to the console, but it should show us if its a failure with the payload or if its never making it to the ApiServer process.

**Comment by ivanhoe** [comment]
Hi @zachdaniel thank you very much for your answer, I configure with the verbose option and im receiving this data 
![Screen Shot 2020-09-19 at 15 53 13](https://user-images.githubusercontent.com/138103/93689040-59f9d000-fa90-11ea-9f1c-0a2b125c8c0d.png)
I don't see anything related with ecto queries when im invoking the endpoint, so its never making to the ApiServer process?

**Comment by zachdaniel** [comment]
Ah, I think your attach call is incorrect.

```
    :ok =
      :telemetry.attach(
        "spandex-query-tracer",
        [:elixir_json_schema, :repo_elixir_json_schema, :query], <- this
        &SpandexEcto.TelemetryAdapter.handle_event/4,
        nil
      )

```

Try setting it to `[:elixir_json_schema, :repo, :query]`

**Comment by zachdaniel** [comment]
That doesn't necessarily address the original issue though. @EdBondRSA what is the module name of your repo?

**Comment by ivanhoe** [comment]
@zachdaniel you were right! it works
![Screen Shot 2020-09-19 at 16 41 43](https://user-images.githubusercontent.com/138103/93689749-0b9bff80-fa97-11ea-8da6-ae91a17a1877.png)
So to understand more about the parameters of the list. The first one is the name of my app, the second should be :repo and the third :query?

**Comment by zachdaniel** [comment]
The name is dictated by ecto, see the `telemetry_prefix` option here: https://hexdocs.pm/ecto/Ecto.Repo.html

**Comment by ivanhoe** [comment]
Ok I will check it! I appreciate so much for your time to be aware of the community questions

**Comment by zachdaniel** [comment]
Glad to help!

**Comment by ivanhoe** [comment]
Hi @EdBondRSA after all the help from @zachdaniel I understand that in your repo.ex you have something like

`defmodule CloudHarmony.Repo do`

In you application.ex you have to define something like:

```
   :ok =
      :telemetry.attach(
        "spandex-query-tracer",
       [:cloud_harmony, :repo, :query],
        &SpandexEcto.TelemetryAdapter.handle_event/4,
        nil
      )
```

Hope this helps!!

**Comment by cheerfulstoic** [comment]
I'm using `absinthe` for a GraphQL API and I think it might be the case that the `Async` middleware is causing another process to lose the trace, as you said @zachdaniel 

I just tried making a new function which gets `current_context` outside and then inside calles `continue_trace("ecto_query", current_context)`, but it's not working.  But when I look at `SpandexEcto.EctoLogger` I don't see `"ecto_query"` as a name.  I see `"query"`, `"queue"`, and `"run_query"`, and `"decode"` though.  Should it be `"query"` (I'm going to try that now to see, but wanted to ask as well in case I'm not understanding something)?

**Comment by cheerfulstoic** [comment]
Hrmmm, it doesn't seem to work with `"query"` either...

**Comment by cheerfulstoic** [comment]
My function, by the way, that I'm using to intercept the `async` for absinthe:

```
  def traced_async(func) do
    current_context = MyAppWeb.Tracer.current_context()

    Absinthe.Resolution.Helpers.async(fn ->
      MyAppWeb.Tracer.continue_trace("query", current_context)

      func.()
    end)
```

**Comment by zachdaniel** [comment]
Ah, try calling `end_trace` after your async work is done (inside the other process). It doesn't technically end the whole trace, just the portion completed on that process. Forgot to mention it earlier.

**Comment by cheerfulstoic** [comment]
I'm trying it now but having some trouble.  When you say "inside the other process" you mean inside of the anonymous function?  Like this:

```ruby
  def traced_async(func) do
    current_context = MyAppWeb.Tracer.current_context()

    Absinthe.Resolution.Helpers.async(fn ->
      MyAppWeb.Tracer.continue_trace("query", current_context)

      value = func.()

      RutilexWeb.Tracer.finish_trace()

      value
    end)
```

When I do that I get an error: `Elixir.Protocol.UndefinedError protocol Msgpax.Packer not implemented for {:ok, %Spandex.SpanContext{...`

**Comment by zachdaniel** [comment]
I think my example was just wrong is all:
`{:ok, current_context} = MyAppWeb.Tracer.current_context()`

**Comment by cheerfulstoic** [comment]
👍  Thanks!  I think that's definitely working better.  I think I have at least one more place where queries aren't being logged, but this should be helpful for that place too once I find it 😄 

For you / anybody else coming along, here's what I ended up with with some error handling bits:

```elixir
    case MyAppWeb.Tracer.current_context() do
      {:ok, current_context} ->
        Absinthe.Resolution.Helpers.async(fn ->
          MyAppWeb.Tracer.continue_trace("query", current_context)

          try do
            func.()
          after
            MyAppWeb.Tracer.finish_trace()
          end
        end)

      {:error, _reason} ->
        Absinthe.Resolution.Helpers.async(fn -> func.() end)
    end
```

**Comment by GregMefford** [comment]
I'll go ahead and close this as it seems like the issue was with trace context propagation and not actually an issue in `spandex_ecto`. Sorry that wasn't easier to understand, though! 😅 We really ought to have a macro that does that propagation for you more easily.
